// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Abysslink Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package evidence_test

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/abysslink/abysslink/internal/audit"
	"github.com/abysslink/abysslink/internal/evidence"
	"github.com/abysslink/abysslink/internal/secrets"
)

// FuzzEvidenceVerify feeds arbitrary/mutated `.alevidence` bytes to
// evidence.Verify and asserts it (a) NEVER panics and (b) NEVER returns Valid
// for a bundle whose signature/fingerprint/content-pins do not actually hold
// (P-C1).
//
// SETUP: a KNOWN-GOOD bundle is built once from the real Create path over a small
// signed audit chain and registered as a corpus seed via f.Add(golden). The
// ed25519 signing key is lazily generated by Create from crypto/rand and lives
// ONLY in an in-memory secrets.MockStore — never a live OS keychain, and never a
// static key literal on disk or in the corpus, so gitleaks stays clean.
//
// WHY THE ORACLE IS PROCESS-INDEPENDENT (does NOT compare against a
// closure-captured golden manifest): Go's fuzzing engine re-runs this setup body
// in every worker process, each with its OWN random signing key, while the seed
// corpus bytes are shared across processes. Because evidence.Verify is
// self-contained (it verifies the pubkey EMBEDDED in the bundle, needing no
// external key), the coordinator's golden bundle verifies Valid=true in a worker
// too — but with a DIFFERENT embedded fingerprint than that worker's own golden.
// Capturing a golden manifest in the closure and asserting equality would
// therefore fire a FALSE failure on cross-process replay. Instead the oracle
// derives every expected quantity from the input b itself.
//
// SOUND FALSE-VALID ORACLE (one-directional; every assertion is a NECESSARY
// condition of a correct Valid verdict, so there are ZERO false failures):
// whenever Verify returns Valid, we independently re-extract the bundle's four
// members from b and confirm, from those bytes alone, that (1) the ed25519
// signature verifies over the exact manifest.json bytes under the embedded
// pubkey, (2) the embedded fingerprint equals KeyFingerprint(pubkey) and equals
// res.Fingerprint, (3) both pinned content hashes match their files, and (4)
// res.Manifest equals the bundle's own parsed manifest. The fuzzer cannot forge
// an ed25519 signature, so a genuine Valid can only arise from a bundle that
// satisfies all of these. It CATCHES a real regression: if Verify ever regressed
// to skip the signature check, accept a fingerprint/pubkey mismatch, or skip a
// content-hash pin, a mutated bundle would return Valid=true while the
// corresponding independent check here fails, and the assertion fires.
func FuzzEvidenceVerify(f *testing.F) {
	ctx := context.Background()

	kc := secrets.NewMockStore()
	logPath := filepath.Join(f.TempDir(), "audit.log")
	sa, err := audit.NewSigned(logPath, kc)
	if err != nil {
		f.Fatal(err)
	}
	for i := 0; i < 3; i++ {
		sum := sha256.Sum256([]byte(fmt.Sprintf("content-%d", i)))
		if aerr := sa.Append(ctx, audit.SignInput{Title: "write", DiffHash: sum},
			fmt.Sprintf("/tmp/target-%d", i), false); aerr != nil {
			f.Fatal(aerr)
		}
	}
	var buf bytes.Buffer
	if _, cerr := evidence.Create(ctx, kc, makeOpts(logPath), &buf); cerr != nil {
		f.Fatal(cerr)
	}
	golden := buf.Bytes()

	if base, verr := evidence.Verify(bytes.NewReader(golden)); verr != nil || !base.Valid {
		f.Fatalf("golden bundle must verify valid at init: err=%v result=%+v", verr, base)
	}

	f.Add(golden)
	f.Add([]byte(""))
	f.Add([]byte("x"))
	f.Add(golden[:len(golden)/2]) // truncated gzip stream
	f.Add(flipLastByte(golden))   // corrupted gzip trailer

	f.Fuzz(func(t *testing.T, b []byte) {
		if len(b) > 1<<16 {
			return // guard against CI OOM -- MUST be the first statement
		}
		// Property: Verify must never panic. An error is allowed (bad gzip/tar or
		// the 512 MiB decompression-bomb guard); Verify already returns Valid=false
		// on every logical failure.
		res, _ := evidence.Verify(bytes.NewReader(b))
		if !res.Valid {
			return
		}
		assertGenuinelyValid(t, b, res)
	})
}

// assertGenuinelyValid re-derives, from b alone, every check a correct Valid
// verdict implies, and fails if any does not hold. Split out to keep the fuzz
// callback under the cyclomatic-complexity gate.
func assertGenuinelyValid(t *testing.T, b []byte, res evidence.VerifyResult) {
	t.Helper()
	files, ok := readBundleFiles(b)
	require.True(t, ok, "Verify returned Valid but the bundle could not be re-read")

	mb, mok := files["manifest.json"]
	sigB64, sok := files["manifest.sig"]
	require.True(t, mok && sok, "a Valid bundle must contain manifest.json and manifest.sig")

	var m evidence.Manifest
	require.NoError(t, json.Unmarshal(mb, &m), "a Valid bundle's manifest must be valid JSON")
	require.Equal(t, "ed25519", m.Signing.Algo)

	pub, perr := base64.StdEncoding.DecodeString(m.Signing.PublicKey)
	require.NoError(t, perr)
	require.Len(t, pub, ed25519.PublicKeySize)

	fp := evidence.KeyFingerprint(pub)
	require.Equal(t, fp, m.Signing.Fingerprint, "Valid bundle: embedded fingerprint must match its pubkey")
	require.Equal(t, fp, res.Fingerprint, "Verify must surface the bundle's own key fingerprint")

	sig, serr := base64.StdEncoding.DecodeString(string(sigB64))
	require.NoError(t, serr)
	require.Len(t, sig, ed25519.SignatureSize)
	require.True(t, ed25519.Verify(ed25519.PublicKey(pub), mb, sig),
		"Verify returned Valid but the ed25519 signature does not actually verify over manifest.json")

	require.Equal(t, m.Contents.AuditLogSHA256, hexSHA256(files["audit.jsonl"]),
		"Verify returned Valid but the pinned audit.jsonl hash does not match its bytes")
	require.Equal(t, m.Contents.ReportSHA256, hexSHA256(files["report.md"]),
		"Verify returned Valid but the pinned report.md hash does not match its bytes")

	require.Equal(t, m, res.Manifest, "Verify's returned Manifest must equal the bundle's own manifest")
}

// readBundleFiles decompresses and untars b into a name→bytes map using the same
// stdlib readers Verify uses. Reads are bounded only by the 64 KiB input guard in
// the fuzz callback. ok is false on any gzip/tar error.
func readBundleFiles(b []byte) (map[string][]byte, bool) {
	gz, err := gzip.NewReader(bytes.NewReader(b))
	if err != nil {
		return nil, false
	}
	defer func() { _ = gz.Close() }()
	tr := tar.NewReader(gz)
	out := map[string][]byte{}
	for {
		hdr, terr := tr.Next()
		if terr == io.EOF {
			break
		}
		if terr != nil {
			return nil, false
		}
		body, rerr := io.ReadAll(tr)
		if rerr != nil {
			return nil, false
		}
		out[hdr.Name] = body
	}
	return out, true
}

// hexSHA256 mirrors the product's content-hash encoding (lowercase hex SHA-256).
func hexSHA256(b []byte) string {
	return fmt.Sprintf("%x", sha256.Sum256(b))
}

// flipLastByte returns a copy of b with its final byte inverted — a cheap way to
// corrupt the gzip trailer while keeping the input near-golden-sized.
func flipLastByte(b []byte) []byte {
	if len(b) == 0 {
		return b
	}
	out := append([]byte(nil), b...)
	out[len(out)-1] ^= 0xff
	return out
}
