//go:build webui

// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Abysslink Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go generate; DO NOT EDIT.

package webui

// HTMXIntegrity is the SHA-384 Subresource Integrity attribute for the embedded
// htmx.min.js. The value is regenerated by `go generate ./internal/modules/webui/...`
// after vendoring htmx (Plan 03) and verified at build time by `make check-htmx-sri`.
// Value verified via: openssl dgst -sha384 -binary assets/htmx.min.js | openssl base64 -A
const HTMXIntegrity = "sha384-H5SrcfygHmAuTDZphMHqBJLc3FhssKjG7w/CeCpFReSfwBWDTKpkzPP8c+cLsK+V"
